title: CocoaGems
description: This is a blog about Team CocoaGems RGSoC experience

url: http://github.com/cocoagems
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: cocoagems
   twitter: cocoagems
   email: cocoagemsrailsgirls@gmail.com

google_analytics: "UA-58263416-1"
